import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Istock',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/istockphoto-.jpg',
    tags: ['Starters'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['Main Dishes'],
  },
  {
    id:'3',
    name: 'Queues de crevettes',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['France'],
    stars: 3.5,
    imageUrl: 'assets/idee-menu-de-Noel-entree-plat-dessert-2.jpg',
    tags: ['Starters'],
  },
  {
    id:'4',
    name: 'Foie Gras',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/foie-gras.webp',
    tags: ['Starters'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/soupe-entree.jpg',
    tags: ['Starters'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['Main Dishes'],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['Main Dishes'],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['Main Dishes'],
  },
  {
    id:'9',
    name: 'Mojito',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['mexico'],
    stars: 4.0,
    imageUrl: 'assets/drinksmojito.jpg',
    tags: ['Drinks'],
  },
  {
    id:'10',
    name: 'Hawaiian',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['mexico'],
    stars: 4.0,
    imageUrl: 'assets/drinks-hawaiian.jpg',
    tags: ['Drinks'],
  },
  {
    id:'11',
    name: 'Cheese Cake',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/cheese cake.jpg',
    tags: ['Desserts'],
  },
  {
    id:'12',
    name: 'Entremets Chocolat Noir',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/dessert-entremets-chocolat-noir-fruits-exotiques_0.jpg',
    tags: ['Desserts'],
  },
  {
    id:'13',
    name: 'Dessert ',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['France'],
    stars: 4.0,
    imageUrl: 'assets/dessert.webp',
    tags: ['Desserts'],
  },
]



export const sample_tags:Tag[] = [
  { name: 'All', count: 13 },
  { name: 'Starters', count: 4 },
  { name: 'Main Dishes', count: 4 },
  { name: 'Drinks', count: 2 },
  { name: 'Desserts', count: 3 }
]

