import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Istock',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/istockphoto-.jpg',
    tags: ['Starter'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['main dishes'],
  },
  {
    id:'3',
    name: 'Queues de crevettes',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['France'],
    stars: 3.5,
    imageUrl: 'assets/idee-menu-de-Noel-entree-plat-dessert-2.jpg',
    tags: ['Starter'],
  },
  {
    id:'4',
    name: 'Foie Gras',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/foie-gras.webp',
    tags: ['Starter'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/soupe-entree.jpg',
    tags: ['Starter'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['main dishes'],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['main dishes'],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['main dishes'],
  },
]

// export const sample_tags:Tag[] = [
//   { name: 'All', count: 8 },
//   { name: 'Starter', count: 4 },
//   { name: 'Pizza', count: 3 },
//   { name: 'Lunch', count: 3 },
//   { name: 'SlowFood', count: 2 },
//   { name: 'Hamburger', count: 2 },
//   { name: 'Fry', count: 1 },
//   { name: 'Soup', count: 1 },
// ]

export const sample_tags:Tag[] = [
  { name: 'All', count: 8 },
  { name: 'Starter', count: 4 },
  { name: 'main dishes', count: 3 },
  { name: 'drinks', count: 3 },
  
]